from typing import Protocol

from call_llm_api.domain.models import (
  AgentProfileRecord,
  BenchmarkCaseRecord,
  BenchmarkCaseResultRecord,
  BenchmarkRunRecord,
  ModelRegistryRecord,
  RunRecord,
  ThreadRecord,
  BenchmarkSuiteRecord,
)


class RunRepository(Protocol):
  async def save(self, run: RunRecord) -> RunRecord: ...

  async def get(self, run_id: str) -> RunRecord | None: ...

  async def list_runs(self) -> list[RunRecord]: ...


class ThreadRepository(Protocol):
  async def save(self, thread: ThreadRecord) -> ThreadRecord: ...

  async def get(self, thread_id: str) -> ThreadRecord | None: ...

  async def list_threads(self) -> list[ThreadRecord]: ...


class ModelRegistryRepository(Protocol):
  async def save(self, model: ModelRegistryRecord) -> ModelRegistryRecord: ...

  async def get(self, model_id: str) -> ModelRegistryRecord | None: ...

  async def list_models(self) -> list[ModelRegistryRecord]: ...


class AgentProfileRepository(Protocol):
  async def save(self, profile: AgentProfileRecord) -> AgentProfileRecord: ...

  async def get(self, profile_id: str) -> AgentProfileRecord | None: ...

  async def list_profiles(self) -> list[AgentProfileRecord]: ...


class BenchmarkSuiteRepository(Protocol):
  async def save_suite(self, suite: BenchmarkSuiteRecord) -> BenchmarkSuiteRecord: ...

  async def get_suite(self, suite_id: str) -> BenchmarkSuiteRecord | None: ...

  async def list_suites(self) -> list[BenchmarkSuiteRecord]: ...

  async def save_case(self, case: BenchmarkCaseRecord) -> BenchmarkCaseRecord: ...

  async def get_case(self, case_id: str) -> BenchmarkCaseRecord | None: ...

  async def list_cases(self, suite_id: str) -> list[BenchmarkCaseRecord]: ...


class BenchmarkRunRepository(Protocol):
  async def save_run(self, run: BenchmarkRunRecord) -> BenchmarkRunRecord: ...

  async def get_run(self, run_id: str) -> BenchmarkRunRecord | None: ...

  async def list_runs(self) -> list[BenchmarkRunRecord]: ...

  async def save_case_result(self, result: BenchmarkCaseResultRecord) -> BenchmarkCaseResultRecord: ...

  async def list_case_results(self, run_id: str) -> list[BenchmarkCaseResultRecord]: ...
