from collections.abc import AsyncIterator
from typing import Protocol


class LLMProvider(Protocol):
  async def list_models(self) -> dict: ...

  async def create_chat_completion(self, payload: dict) -> dict: ...

  async def close(self) -> None: ...

  def forward_chat_completion_stream(self, payload: dict) -> AsyncIterator[bytes]: ...

  def stream_chat_completion_chunks(self, payload: dict) -> AsyncIterator[dict]: ...
